services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  api:
    build: .
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
    restart: always

volumes:
  postgres_data: